# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editusers.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editUsersWindow(object):
    def setupUi(self, editUsersWindow):
        editUsersWindow.setObjectName("editUsersWindow")
        editUsersWindow.resize(1123, 744)
        editUsersWindow.setStyleSheet("QPushButton {padding: 10px}\n"
"QWidget {background-color: white}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(editUsersWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 3, 3, 1)
        self.pushButton_2 = QtWidgets.QPushButton(editUsersWindow)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 5, 1, 1, QtCore.Qt.AlignRight)
        self.label_12 = QtWidgets.QLabel(editUsersWindow)
        self.label_12.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 4, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(editUsersWindow)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.phoneCall = QtWidgets.QLineEdit(editUsersWindow)
        self.phoneCall.setObjectName("phoneCall")
        self.gridLayout_2.addWidget(self.phoneCall, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(editUsersWindow)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(editUsersWindow)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(editUsersWindow)
        self.email.setObjectName("email")
        self.gridLayout_2.addWidget(self.email, 1, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(editUsersWindow)
        self.name.setEnabled(False)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(editUsersWindow)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.phoneWhatsApp = QtWidgets.QLineEdit(editUsersWindow)
        self.phoneWhatsApp.setObjectName("phoneWhatsApp")
        self.gridLayout_2.addWidget(self.phoneWhatsApp, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(editUsersWindow)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.roomNumber = QtWidgets.QLineEdit(editUsersWindow)
        self.roomNumber.setObjectName("roomNumber")
        self.gridLayout_2.addWidget(self.roomNumber, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 4, 1, 2)
        self.itemView = QtWidgets.QListView(editUsersWindow)
        self.itemView.setMinimumSize(QtCore.QSize(350, 0))
        self.itemView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.itemView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.itemView.setAlternatingRowColors(True)
        self.itemView.setObjectName("itemView")
        self.gridLayout.addWidget(self.itemView, 4, 2, 3, 1)
        self.userView = QtWidgets.QListView(editUsersWindow)
        self.userView.setMinimumSize(QtCore.QSize(350, 0))
        self.userView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.userView.setAlternatingRowColors(True)
        self.userView.setObjectName("userView")
        self.gridLayout.addWidget(self.userView, 4, 0, 3, 2)
        self.label_7 = QtWidgets.QLabel(editUsersWindow)
        self.label_7.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(editUsersWindow)
        self.label.setStyleSheet("font: 24pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 6, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 6)
        self.label_6 = QtWidgets.QLabel(editUsersWindow)
        self.label_6.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(editUsersWindow)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 5, 4, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)

        self.retranslateUi(editUsersWindow)
        QtCore.QMetaObject.connectSlotsByName(editUsersWindow)

    def retranslateUi(self, editUsersWindow):
        _translate = QtCore.QCoreApplication.translate
        editUsersWindow.setWindowTitle(_translate("editUsersWindow", "Form"))
        self.pushButton_2.setText(_translate("editUsersWindow", "Delete User"))
        self.label_12.setText(_translate("editUsersWindow", "Details"))
        self.label_8.setText(_translate("editUsersWindow", "Phone (Calling)"))
        self.label_9.setText(_translate("editUsersWindow", "Phone (WhatsApp)"))
        self.label_10.setText(_translate("editUsersWindow", "Email"))
        self.label_5.setText(_translate("editUsersWindow", "Name"))
        self.label_11.setText(_translate("editUsersWindow", "Room Number"))
        self.label_7.setText(_translate("editUsersWindow", "Items Checked Out"))
        self.label.setText(_translate("editUsersWindow", "Edit Users"))
        self.label_6.setText(_translate("editUsersWindow", "Users"))
        self.checkBox.setText(_translate("editUsersWindow", "Administrator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editUsersWindow = QtWidgets.QWidget()
    ui = Ui_editUsersWindow()
    ui.setupUi(editUsersWindow)
    editUsersWindow.show()
    sys.exit(app.exec_())

