# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory_editor.ui'
#
# Created: Mon Jan  1 14:43:35 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_inventoryEditor(object):
    def setupUi(self, inventoryEditor):
        inventoryEditor.setObjectName("inventoryEditor")
        inventoryEditor.resize(1164, 672)
        inventoryEditor.setStyleSheet("QPushButton {padding: 10px}\n"
"QWidget {background-color: white}\n"
"")
        self.centralwidget = QtWidgets.QWidget(inventoryEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 3, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.gridLayout_3.addWidget(self.status, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.itemListView = QtWidgets.QListView(self.centralwidget)
        self.itemListView.setMinimumSize(QtCore.QSize(350, 0))
        self.itemListView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.itemListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.itemListView.setAlternatingRowColors(True)
        self.itemListView.setObjectName("itemListView")
        self.gridLayout_2.addWidget(self.itemListView, 3, 1, 3, 1)
        self.partCategory = QtWidgets.QLineEdit(self.centralwidget)
        self.partCategory.setAlignment(QtCore.Qt.AlignCenter)
        self.partCategory.setObjectName("partCategory")
        self.gridLayout_2.addWidget(self.partCategory, 4, 3, 1, 1)
        self.partName = QtWidgets.QLineEdit(self.centralwidget)
        self.partName.setAlignment(QtCore.Qt.AlignCenter)
        self.partName.setObjectName("partName")
        self.gridLayout_2.addWidget(self.partName, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 24pt \"Noto Sans\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.categoryView = QtWidgets.QListView(self.centralwidget)
        self.categoryView.setMinimumSize(QtCore.QSize(350, 0))
        self.categoryView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.categoryView.setAlternatingRowColors(True)
        self.categoryView.setObjectName("categoryView")
        self.gridLayout_2.addWidget(self.categoryView, 3, 0, 3, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.new_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_2.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_2.setIcon(icon)
        self.new_2.setObjectName("new_2")
        self.horizontalLayout.addWidget(self.new_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(14)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.rfid = QtWidgets.QLineEdit(self.centralwidget)
        self.rfid.setObjectName("rfid")
        self.gridLayout.addWidget(self.rfid, 5, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Delete.setDefault(False)
        self.Delete.setObjectName("Delete")
        self.horizontalLayout_9.addWidget(self.Delete)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Save.setObjectName("Save")
        self.horizontalLayout_9.addWidget(self.Save)
        self.gridLayout.addLayout(self.horizontalLayout_9, 12, 0, 1, 2)
        self.partID = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.partID.setFont(font)
        self.partID.setText("")
        self.partID.setAlignment(QtCore.Qt.AlignCenter)
        self.partID.setObjectName("partID")
        self.gridLayout.addWidget(self.partID, 2, 1, 1, 1)
        self.partShelf = QtWidgets.QLineEdit(self.centralwidget)
        self.partShelf.setAlignment(QtCore.Qt.AlignCenter)
        self.partShelf.setObjectName("partShelf")
        self.gridLayout.addWidget(self.partShelf, 3, 1, 1, 1)
        self.partImage = QtWidgets.QLabel(self.centralwidget)
        self.partImage.setMaximumSize(QtCore.QSize(130, 130))
        self.partImage.setText("")
        self.partImage.setPixmap(QtGui.QPixmap("images/default_item.png"))
        self.partImage.setScaledContents(True)
        self.partImage.setObjectName("partImage")
        self.gridLayout.addWidget(self.partImage, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.minus.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minus.setIcon(icon1)
        self.minus.setObjectName("minus")
        self.horizontalLayout_2.addWidget(self.minus)
        self.quantity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity.setFont(font)
        self.quantity.setScaledContents(False)
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout_2.addWidget(self.quantity)
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plus.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plus.setIcon(icon2)
        self.plus.setObjectName("plus")
        self.horizontalLayout_2.addWidget(self.plus)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 10, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.partBox = QtWidgets.QLineEdit(self.centralwidget)
        self.partBox.setAlignment(QtCore.Qt.AlignCenter)
        self.partBox.setObjectName("partBox")
        self.gridLayout.addWidget(self.partBox, 4, 1, 1, 1)
        self.rfidButton = QtWidgets.QPushButton(self.centralwidget)
        self.rfidButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/rfid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rfidButton.setIcon(icon3)
        self.rfidButton.setObjectName("rfidButton")
        self.gridLayout.addWidget(self.rfidButton, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        inventoryEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(inventoryEditor)
        QtCore.QMetaObject.connectSlotsByName(inventoryEditor)
        inventoryEditor.setTabOrder(self.categoryView, self.itemListView)

    def retranslateUi(self, inventoryEditor):
        _translate = QtCore.QCoreApplication.translate
        inventoryEditor.setWindowTitle(_translate("inventoryEditor", "MainWindow"))
        self.partCategory.setPlaceholderText(_translate("inventoryEditor", "Category"))
        self.partName.setPlaceholderText(_translate("inventoryEditor", "Item Name"))
        self.label_2.setText(_translate("inventoryEditor", "Inventory Editor"))
        self.new_2.setText(_translate("inventoryEditor", "New"))
        self.label_6.setText(_translate("inventoryEditor", "Category"))
        self.label_7.setText(_translate("inventoryEditor", "Item"))
        self.Delete.setText(_translate("inventoryEditor", "Delete"))
        self.Save.setText(_translate("inventoryEditor", "Save"))
        self.label.setText(_translate("inventoryEditor", "Available Quantity"))
        self.label_4.setText(_translate("inventoryEditor", "Shelf:"))
        self.quantity.setText(_translate("inventoryEditor", " 1 "))
        self.label_5.setText(_translate("inventoryEditor", "Box:"))
        self.label_3.setText(_translate("inventoryEditor", "ID:"))
        self.rfidButton.setText(_translate("inventoryEditor", "RFID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inventoryEditor = QtWidgets.QMainWindow()
    ui = Ui_inventoryEditor()
    ui.setupUi(inventoryEditor)
    inventoryEditor.show()
    sys.exit(app.exec_())

