# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectsBrowser.ui'
#
# Created: Fri Oct 27 13:31:56 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editUsersWindow(object):
    def setupUi(self, editUsersWindow):
        editUsersWindow.setObjectName("editUsersWindow")
        editUsersWindow.resize(1151, 829)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(editUsersWindow.sizePolicy().hasHeightForWidth())
        editUsersWindow.setSizePolicy(sizePolicy)
        editUsersWindow.setStyleSheet("QPushButton {padding: 10px}\n"
"QWidget {background-color: white}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(editUsersWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(editUsersWindow)
        self.label.setStyleSheet("font: 24pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 4, QtCore.Qt.AlignHCenter)
        self.userView = QtWidgets.QListView(editUsersWindow)
        self.userView.setMinimumSize(QtCore.QSize(350, 0))
        self.userView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.userView.setAlternatingRowColors(True)
        self.userView.setObjectName("userView")
        self.gridLayout.addWidget(self.userView, 3, 1, 2, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deleteButton = QtWidgets.QPushButton(editUsersWindow)
        self.deleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.deleteButton.setAutoFillBackground(False)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_2.addWidget(self.deleteButton, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(editUsersWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(editUsersWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.ViewCart = QtWidgets.QPushButton(editUsersWindow)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.ViewCart.setFont(font)
        self.ViewCart.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ViewCart.setObjectName("ViewCart")
        self.gridLayout_2.addWidget(self.ViewCart, 5, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(editUsersWindow)
        self.name.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 2, 1, 1, 1)
        self.Inventory = QtWidgets.QPushButton(editUsersWindow)
        self.Inventory.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Inventory.setObjectName("Inventory")
        self.gridLayout_2.addWidget(self.Inventory, 4, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(editUsersWindow)
        self.saveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.new_2 = QtWidgets.QPushButton(editUsersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_2.sizePolicy().hasHeightForWidth())
        self.new_2.setSizePolicy(sizePolicy)
        self.new_2.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_2.setIcon(icon)
        self.new_2.setObjectName("new_2")
        self.horizontalLayout.addWidget(self.new_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(editUsersWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 3, 1, 2)
        self.pushButton = QtWidgets.QPushButton(editUsersWindow)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/usernew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 5, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(editUsersWindow)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 1, 1, 1)

        self.retranslateUi(editUsersWindow)
        QtCore.QMetaObject.connectSlotsByName(editUsersWindow)

    def retranslateUi(self, editUsersWindow):
        _translate = QtCore.QCoreApplication.translate
        editUsersWindow.setWindowTitle(_translate("editUsersWindow", "Form"))
        self.label.setText(_translate("editUsersWindow", "Projects List"))
        self.deleteButton.setText(_translate("editUsersWindow", "Delete Project"))
        self.label_5.setText(_translate("editUsersWindow", "Name"))
        self.label_10.setText(_translate("editUsersWindow", "Project Lead"))
        self.ViewCart.setText(_translate("editUsersWindow", "View Cart"))
        self.Inventory.setText(_translate("editUsersWindow", "Add Items"))
        self.saveButton.setText(_translate("editUsersWindow", "Save Details"))
        self.new_2.setText(_translate("editUsersWindow", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editUsersWindow = QtWidgets.QWidget()
    ui = Ui_editUsersWindow()
    ui.setupUi(editUsersWindow)
    editUsersWindow.show()
    sys.exit(app.exec_())

